apiVersion: v2
name: loyaltyos
description: LoyaltyOS — Open source customer loyalty platform with native coalition support
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.27.0-0"
icon: https://raw.githubusercontent.com/jvillatox/loyaltyos/main/docs-site/static/img/logo.svg
home: https://github.com/jvillatox/loyaltyos
sources:
  - https://github.com/jvillatox/loyaltyos
keywords:
  - loyalty
  - points
  - coalition
  - rewards
  - coupons
  - gamification
maintainers:
  - name: jvillatox
    url: https://github.com/jvillatox

dependencies:
  - name: postgresql
    version: "16.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "20.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
