{{- if .Values.bullmqWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loyaltyos.fullname" . }}-bullmq-worker
  labels:
    {{- include "loyaltyos.bullmqWorker.labels" . | nindent 4 }}
  {{- with .Values.bullmqWorker.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.bullmqWorker.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "loyaltyos.bullmqWorker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "loyaltyos.bullmqWorker.selectorLabels" . | nindent 8 }}
        {{- with .Values.bullmqWorker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.bullmqWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "loyaltyos.fullname" . }}-api
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: bullmq-worker
          image: {{ include "loyaltyos.image" (dict "imageRoot" .Values.bullmqWorker.image "Values" .Values "Chart" .Chart) }}
          imagePullPolicy: {{ .Values.bullmqWorker.image.pullPolicy }}
          command: {{ .Values.bullmqWorker.command | toJson }}
          envFrom:
            - configMapRef:
                name: {{ include "loyaltyos.fullname" . }}-api-config
            - secretRef:
                name: {{ include "loyaltyos.fullname" . }}-api-secret
          resources:
            {{- toYaml .Values.bullmqWorker.resources | nindent 12 }}
      {{- with .Values.bullmqWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bullmqWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bullmqWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
