{{- if .Values.api.enabled }}
{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loyaltyos.fullname" . }}-api-secret
  labels:
    {{- include "loyaltyos.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.env.JWT_SECRET | required "api.env.JWT_SECRET is required" | quote }}
  API_KEY_SALT: {{ .Values.api.env.API_KEY_SALT | required "api.env.API_KEY_SALT is required" | quote }}
  KMS_MASTER_KEY: {{ .Values.api.env.KMS_MASTER_KEY | required "api.env.KMS_MASTER_KEY is required" | quote }}
  {{- if .Values.api.env.RESEND_API_KEY }}
  RESEND_API_KEY: {{ .Values.api.env.RESEND_API_KEY | quote }}
  {{- end }}
  {{- if .Values.api.env.TWILIO_ACCOUNT_SID }}
  TWILIO_ACCOUNT_SID: {{ .Values.api.env.TWILIO_ACCOUNT_SID | quote }}
  {{- end }}
  {{- if .Values.api.env.TWILIO_AUTH_TOKEN }}
  TWILIO_AUTH_TOKEN: {{ .Values.api.env.TWILIO_AUTH_TOKEN | quote }}
  {{- end }}
  {{- if .Values.api.env.ONESIGNAL_APP_ID }}
  ONESIGNAL_APP_ID: {{ .Values.api.env.ONESIGNAL_APP_ID | quote }}
  {{- end }}
  {{- if .Values.api.env.ONESIGNAL_API_KEY }}
  ONESIGNAL_API_KEY: {{ .Values.api.env.ONESIGNAL_API_KEY | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  {{- if .Values.postgresql.auth.password }}
  DATABASE_URL: {{ include "loyaltyos.databaseUrl" . | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.externalDatabase.enabled }}
  DATABASE_URL: {{ include "loyaltyos.databaseUrl" . | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.auth.password }}
  REDIS_URL: {{ include "loyaltyos.redisUrl" . | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.externalRedis.enabled }}
  REDIS_URL: {{ include "loyaltyos.redisUrl" . | quote }}
  {{- end }}
{{- end }}

{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "loyaltyos.fullname" . }}-api-secret
  labels:
    {{- include "loyaltyos.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ include "loyaltyos.fullname" . }}-api-secret
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.keys }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
    {{- end }}
{{- end }}
{{- end }}
